### PR TITLE
Remove `pre_mt` parameter

### PR DESCRIPTION
**Pull request by toshipon**
Because API doesn't support this parameter anymore.

### CODE REVIEW

**Comment by patatepartie** [comment]
LGTM except build not passing

**Comment by ninotoshi** [comment]
LGTM except the tests that started to fail 4 months ago.

**Comment by hayate** [comment]
@toshipon do you have time to look into why the tests are failing?

**Comment by ninotoshi** [comment]
@toshipon has some stuff to be done by tomorrow, I think I can take this on.
(this PR should be able to be merged now)

**Comment by toshipon** [comment]
@ninotoshi thank you for fixing the errors ! 🙇

**Pull request merged**
