### PR TITLE
Authorization using access token from OAuth

### PR DESCRIPTION
**Pull request by over**

### CODE REVIEW

**Comment by toshipon** [comment]
@over 
Thank you for your contributing ! 
would you mind merging latest master on your branch to fix current build error ? 
I've fixed the issue temporary. 
https://github.com/gengo/gengo-ruby/pull/36

Thank you

**Comment by over** [comment]
@toshipon just did, looks like now it is ok

**Comment by over** [comment]
@toshipon are you going to merge this request?

**Comment by toshipon** [comment]
@over sorry for delay! yes I'm going to merge the PR. 
Thank you for your contribution!

**Comment by toshipon** [comment]
@over hi, your change is available on https://rubygems.org/gems/gengo/versions/0.2.0 now

**Pull request merged**
