### PR TITLE
Use SSL for all request

### PR DESCRIPTION
**Pull request by takp**
Hi I think it's better to use SSL.
Tell me if any change is needed. Thanks.

### CODE REVIEW

**Comment by takp** [comment]
Is anyone watching? Should I fix the .travis.yml ?

**Comment by hayate** [comment]
@takp I am sorry for late reply. Yes could you please make sure travis-ci build passes?

**Comment by takp** [comment]
@hayate 
Thanks for the reply. I'm trying to pass the travis, but it doesn't work well.

The test failed because the GENGO_PUBKEY was not set, though I haven't change the `.travis.yml` .

I think this is because the encrypted variables can not be available for  the pull requests from the other repository.

>Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.
https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

And, This `.travis.yml` was changed to use the encrypted variables by this commit:  https://github.com/gengo/gengo-ruby/commit/0a1f1cf75fc12381c47589d73aba0f689d66c5f9

So... Should I change the `.travis.yml` not to use the encrypted variables?
Would you please give me an advise?

**Comment by toshipon** [comment]
@takp 
Sorry for delay to reply again. 
yes, seems travis doesn't provide easy way to fix this case.
I've found following conversation and they mentioned about `jwt` addon however Gengo API doesn't have this way now. 
https://docs.travis-ci.com/user/jwt
https://github.com/travis-ci/travis-ci/issues/1946

So that please take non-encrypted keys back from https://github.com/gengo/gengo-ruby/commit/0a1f1cf75fc12381c47589d73aba0f689d66c5f9 and use them ? Sorry it's my bad..

Thank you for great contribution :bow:

**Comment by takp** [comment]
@toshipon 
Oh I didn't know the `jwt`, it looks nice.
I have reverted the `.travis.yml`, please check this. Thank you.

**Comment by toshipon** [comment]
Thank you for your changes! LGTM :bow:

**Comment by toshipon** [comment]
I've published new version :bow:
https://rubygems.org/gems/gengo/versions/0.2.1

**Comment by takp** [comment]
Thank you!!

**Pull request merged**
