### PR TITLE
[#93591580] Fix minor issues in v2/translate/order/:id

### PR DESCRIPTION
**Pull request by yugui**
* Fixed a wrong description of parameter
* Fixed RDoc(Yard) syntax issues
* Deprecated some methods with wrong design
* Added new methods with more Ruby-ish design and stricter parameter
  checking
* Handle exceptions raised while parsing response

### CODE REVIEW

**Comment by yugui** [comment]
@randomwire This PR contains user-facing documentation.
Could you review it from a perspective of UX and English writing?

**Comment by randomwire** [comment]
@yugui I think the English is fine but I don't understand what "shuttling up encoded job data" means below...?

"The "POST" method; handles shuttling up encoded job data to Gengo"

**Comment by yugui** [comment]
It's not a part of this PR and I don't know what it means.

**Comment by hayate** [comment]
thank you LGTM

**Pull request merged**
